name: 'Github Tag Bump'
description: 'Bump and push git tag on merge'
author: 'Nick Sjostrom'
runs:
  using: 'docker'
  image: 'Dockerfile'
outputs:
  new_tag:
    description: 'Generated tag'
  new_tag_without_prefix:
    description: 'Generated tag without specified prefix'
  tag:
    description: 'The latest tag before running this action'
  part:
    description: 'The part of version which was bumped'
branding:
  icon: 'git-merge'  
  color: 'purple'
